apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-argocd
  namespace: argocd
  annotations:
    # Geeft aan dat deze Ingress afgehandeld moet worden door NGINX
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  # Koppel het externe domein aan de interne ArgoCD service
  - host: gitops.festivalstream.nl
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: argocd-server
            port:
              number: 80
  # Zelfde configuratie, maar dan voor het interne .local domein
  - host: gitops.festivalstream.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: argocd-server
            port:
              number: 80