# Dit is alertmanager, deze service zorgt ervoor dat er een melding wordt gemaakt als er een alert is. 
# Hier wordt beschreven hoe alertmanager wordt gedeployed en welke service er bij hoort.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertmanager
  template:
    metadata:
      labels:
        app: alertmanager
    spec:
      containers:
        - name: alertmanager
          image: prom/alertmanager:v0.28.1
          # De volgende args zijn gebaseerd op de configuratie van alertmanager. Deze args zorgen ervoor dat alertmanager de configuratie gebruikt die is opgegeven in de ConfigMap, zodat alertmanager weet hoe het moet werken en waar het de meldingen naartoe moet sturen.
          args:
            - --config.file=/etc/alertmanager/alertmanager.yml
          ports:
            - containerPort: 9093
          # De volgende volumeMounts zijn gebaseerd op de configuratie van alertmanager. Deze volumeMounts zorgen ervoor dat alertmanager de configuratie kan gebruiken die is opgegeven in de ConfigMap, zodat alertmanager weet hoe het moet werken en waar het de meldingen naartoe moet sturen.
          volumeMounts:
            - name: alertmanager-config
              mountPath: /etc/alertmanager
      volumes:
        - name: alertmanager-config
          configMap:
            name: alertmanager-config