# Grafana Deployment
# Dit is grafana, deze service zorgt ervoor dat er een dashboard is waar je de metrics van Prometheus kunt bekijken.
# Hier wordt beschreven hoe grafana wordt gedeployed en welke service er bij hoort.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: monitoring
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      securityContext:
        runAsUser: 472
        fsGroup: 472
      containers:
        - name: grafana
          image: grafana/grafana:11.5.2
          ports:
            - containerPort: 3000
          # De volgende env vars zijn gebaseerd op de configuratie van grafana. 
          # Deze env vars zorgen ervoor dat grafana de juiste instellingen heeft, zoals bijvoorbeeld de gebruikersnaam en wachtwoord voor het dashboard, en dat grafana geen updates controleert, zodat er geen onverwachte updates worden geïnstalleerd die mogelijk problemen kunnen veroorzaken.
          env:
            - name: GF_SECURITY_ADMIN_USER
              value: admin
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: Welkom01!
            - name: GF_ANALYTICS_CHECK_FOR_UPDATES
              value: "false"
            - name: GF_ANALYTICS_CHECK_FOR_PLUGIN_UPDATES
              value: "false"
          # De volgende volumeMounts zijn gebaseerd op de configuratie van grafana. Deze volumeMounts zorgen ervoor dat grafana de juiste data kan opslaan, zoals bijvoorbeeld dashboards en configuraties.
          volumeMounts:
            - name: grafana-storage
              mountPath: /var/lib/grafana
      volumes:
        - name: grafana-storage
          emptyDir: {}