# Grafana Service
# Hier wordt beschreven hoe andere services de deployment van grafana kunnen bereiken.

apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: monitoring
spec:
  selector:
    app: grafana
  ports:
    - port: 80
      targetPort: 3000
  type: ClusterIP