# Dit is een test pod, deze pod zal 5GB aan geheugen gebruiken en zal 5 minuten lang draaien. 
# Deze pod is bedoeld om te testen of de alert die we hebben gemaakt in Prometheus werkt, deze alert zal afgaan als er meer dan 4GB aan geheugen wordt gebruikt.

apiVersion: v1
kind: Pod
metadata:
  name: ram-geheugen-test
  namespace: monitoring
spec:
  restartPolicy: Never
  containers:
  - name: stress
    image: progrium/stress
    command:
      - stress
    args:
      - --vm
      - "1"
      - --vm-bytes
      - 5G
      - --timeout
      - 300s