apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo-pvc
  namespace: storage-chat
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: truenas-nfs
  resources:
    requests:
      storage: 1Gi