apiVersion: apps/v1
kind: Deployment
metadata:
  name: truenas-demo
  namespace: storage-chat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: persistent-test
  template:
    metadata:
      labels:
        app: persistent-test
    spec:
      volumes:
        - name: truenas-volume
          persistentVolumeClaim:
            claimName: chat-pvc 
      containers:
        - name: alpine-container
          image: alpine
          command: ["/bin/sh", "-c", "while true; do sleep 3600; done"]
          volumeMounts:
            - mountPath: "/data"
              name: truenas-volume